apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "royaai.fullname" . }}-config
  labels:
    {{- include "royaai.labels" . | nindent 4 }}
data:
  # Add your application config settings here
  ASPNETCORE_URLS: "http://+:80" 